pool:
  vmImage: 'windows-latest'

variables:
  - name: MajorMinor
    value: '0.1'
  - name: Patch
    value: $[counter(variables['MajorMinor'], 1)]
  - name: Version
    value: $(MajorMinor).$(Patch)
  - name: BuildConfiguration
    value: 'Release'


steps:
  - task: PowerShell@2
    displayName: 'Update Version For Nuget Packages'
    inputs:
      filePath: 'replace-version.ps1'
      arguments: '$(Version)'

  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK'
    inputs:
      version: 5.0.301

  - script: |
      dotnet restore lib/BlueJay.Core/BlueJay.Core.Nuget.csproj
      dotnet pack lib/BlueJay.Core/BlueJay.Core.Nuget.csproj -c $(BuildConfiguration) -o dist
    displayName: 'Restore and Pack BlueJay.Core'
    
  - task: DotNetCoreCLI@2
    displayName: 'NuGet Push BlueJay.Core'
    inputs:
      command: 'push'
      packagesToPush: 'dist/BlueJay.Core.$(Version).nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'NuGet Service Connection'