pool:
  vmImage: 'windows-latest'

variables:
  - name: MajorMinor
    value: '0.1'
  - name: Patch
    value: $[counter(variables['MajorMinor'], 1)]
  - name: Version
    value: $(MajorMinor).$(Patch)
  - name: BuildConfiguration
    value: 'Release'
  - name: PackLocation
    value: dist
  - name: ApiSource
    value: https://api.nuget.org/v3/index.json


steps:
  - task: PowerShell@2
    displayName: 'Update Version For Nuget Packages'
    inputs:
      filePath: 'replace-version.ps1'
      arguments: '$(Version)'

  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK'
    inputs:
      version: 5.0.301

  - script: |
      dotnet restore lib/BlueJay.Core/BlueJay.Core.Nuget.csproj
      dotnet pack lib/BlueJay.Core/BlueJay.Core.Nuget.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.Core.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.Core'