pool:
  vmImage: 'windows-latest'

variables:
  - name: MajorMinor
    value: '0.2'
  - name: Patch
    value: $[counter(variables['MajorMinor'], 1)]
  - name: Version
    value: $(MajorMinor).$(Patch)
  - name: BuildConfiguration
    value: 'Release'
  - name: PackLocation
    value: dist
  - name: ApiSource
    value: https://api.nuget.org/v3/index.json


steps:
  - task: PowerShell@2
    displayName: 'Update Version For Nuget Packages'
    inputs:
      filePath: 'replace-version.ps1'
      arguments: '$(Version)'

  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK'
    inputs:
      version: 6.0.x

  - script: |
      dotnet restore lib/BlueJay.Core/BlueJay.Core.csproj
      dotnet pack lib/BlueJay.Core/BlueJay.Core.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.Core.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.Core'
  
  - script: |
      dotnet restore lib/BlueJay.Events/BlueJay.Events.csproj
      dotnet pack lib/BlueJay.Events/BlueJay.Events.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.Events.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.Events'
  
  - script: |
      dotnet restore lib/BlueJay.Component.System/BlueJay.Component.System.csproj
      dotnet pack lib/BlueJay.Component.System/BlueJay.Component.System.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.Component.System.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.Component.System'
  
  - script: |
      dotnet restore lib/BlueJay/BlueJay.csproj
      dotnet pack lib/BlueJay/BlueJay.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay'

  - script: |
      dotnet restore lib/BlueJay.UI/BlueJay.UI.csproj
      dotnet pack lib/BlueJay.UI/BlueJay.UI.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.UI.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.UI'

  - script: |
      dotnet restore lib/BlueJay.Common/BlueJay.Common.csproj
      dotnet pack lib/BlueJay.Common/BlueJay.Common.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.Common.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.Common'

  - script: |
      dotnet restore lib/BlueJay.UI.Component/BlueJay.UI.Component.csproj
      dotnet pack lib/BlueJay.UI.Component/BlueJay.UI.Component.csproj -c $(BuildConfiguration) -o $(PackLocation)
      dotnet nuget push $(PackLocation)/BlueJay.UI.Component.$(Version).nupkg --api-key $(APIKEY) --source $(ApiSource)
    displayName: 'Restore, Pack, and Push BlueJay.UI.Component'